# Generated by Django 5.2.3 on 2025-07-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=16)),
                ('Token', models.CharField(max_length=64, null=True)),
                ('FriendRequest', models.CharField(max_length=4000, null=True)),
                ('FriendList', models.CharField(max_length=4000, null=True)),
                ('Privilege', models.CharField(max_length=6)),
                ('BanStatus', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('HistoryID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Opponent_Username', models.CharField(max_length=40)),
                ('Chess_Movement', models.CharField(max_length=1345)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.account')),
            ],
        ),
    ]
